source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!


target 'AegroApp' do
    pod 'RealmSwift'
end

target 'AegroAppTests' do
    pod 'RealmSwift'
    pod 'Quick'
    pod 'Nimble'
end


